[MIG] Migrate module disable_odoo_online to v14.
OCA/server-brand pull request #35
Opened 2020-10-21 14:13 UTC by dsolanki-initos

2020-12-18 05:48 UTC, dsolanki-initos commented
Hello @all
Can anyone please review the PR?

2020-12-18 07:50 UTC, astirpe requested changes

2020-12-18 07:50 UTC, astirpe commented on disable_odoo_online/models/publisher_warranty_contract.py
> +            )
```suggestion
            return super().update_notification(cron_mode=cron_mode)
```

2020-12-18 07:50 UTC, astirpe commented on disable_odoo_online/views/ir_ui_menu.xml
> +    <record model="ir.ui.menu" id="base.menu_module_updates">
Place id attribute before model, according to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#xml-files

2020-12-21 06:18 UTC, dsolanki-initos commented
@astirpe I have resolved the changes suggested.

2020-12-21 07:25 UTC, astirpe approved these changes

2021-01-24 21:23 UTC, bosd approved these changes
Functional review, LGTM :+1:

2021-01-25 07:57 UTC, pedrobaeza commented
/ocabot merge nobump

2021-01-25 08:10 UTC, merged